version: '3'

services:
  barbershop-app:
    container_name: barbershop-app
    build: .
    image: barbershop-app:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=barber
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
